site_name: Receptiviti
site_url: https://receptiviti.github.io/receptiviti-python
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Nunito Sans
    code: SFMono-Regular
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/receptiviti/receptiviti-python
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - mkdocs-jupyter:
      remove_tag_config:
        remove_input_tags:
          - hide_code
        remove_all_outputs_tags:
          - hide_output
        remove_cell_tags:
          - hide_cell
docs_dir: 'docs_source'
site_dir: 'docs'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: README.md
  - Get Started: articles/quick_start.ipynb
  - References:
      - functions/request.md
      - functions/status.md
      - functions/readin_env.md
  - Test Coverage: coverage/index.html
  - Versions:
      - Development: https://receptiviti.github.io/receptiviti-python/
      - 0.1.1: https://receptiviti.github.io/receptiviti-python/v/0.1.1/
      - 0.1.0: https://receptiviti.github.io/receptiviti-python/v/0.1.0/
      - Changelog: CHANGELOG.md
exclude_docs: |
  articles/quick_start.md
